### PR TITLE
Enable simple callback for improved runtime diagnostics

### PR DESCRIPTION
**Pull request by bclothier**
The code uses `fprintf` which may be inadequate in cases where additional runtime diagnostics is needed. To avoid getting too mired in complex error logging, I settled on providing a simple error callback that the consumer can choose to listen to. It is set globally so there can be only one error callback in error. However, this should suffice in providing some data to the caller and therefore additional information from the whitedb not available via return code alone.

### CODE REVIEW

**Comment by priitj** [comment]
Very nice! I think this is the way to do it.

Currently this does not compile unless USE_ERROR_CALLBACK is defined.

I see that some errors have been changed to LOG_ERROR macros and others have not. Would it make sense to change all writes to stderr from the library to LOG_ERROR macros?

Also, I think I'd probably make it so that the callback replaces the write to stderr and that the WG_NO_ERRPRINT can suppress the write to stderr (in that case there would be no error output at all). But this is definitely open to discussion.

**Comment by priitj** [comment]
To clarify: If USE_ERROR_CALLBACK is in config files, it is implied that it is a user configurable feature. However, if the user chooses to disable that feature, the code will not compile.

It should either compile without that macro defined, or the macro should not be in config files (i.e. simply a macro that helps organizing code features for the developer).

**Comment by bclothier** [comment]
Thanks for the clarification. I've fixed up the code and also provided a bit more extra checking around setting the callback to make it less confusing in case there's multiple callers trying to snatch away the lone global callback.

A full fledged implementation would probably have it in an array but that is a bit more than I want to do at the moment and I do not need multicast callback myself. Hope others find it useful.

**Comment by priitj** [comment]
I've changed the variadic macro style slightly. IIRC this compiles on MSVC as well, but I can't test it right now since my Windows build environment is not operational. Please let me know if there are any issues on the Windows platform.

Also I removed stdarg.h inclusion, I think this is for the va_* macros.

Regarding the behaviour, the way you solved it seems simplest and safest - old behaviour is unchanged, new behaviour available for those who need it.

**Comment by priitj** [comment]
And thank you for the contribution to the project! :-)

**Pull request merged**
